// Generated by Kukicha (requires Go 1.26+)

package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/cli"
	"github.com/kukichalang/kukicha/stdlib/env"
	"github.com/kukichalang/kukicha/stdlib/fetch"
	"github.com/kukichalang/kukicha/stdlib/files"
	"github.com/kukichalang/kukicha/stdlib/input"
	jsonpkg "github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/kukicha/stdlib/llm"
	"github.com/kukichalang/kukicha/stdlib/mcp"
	"github.com/kukichalang/kukicha/stdlib/netguard"
	"github.com/kukichalang/kukicha/stdlib/sandbox"
	"github.com/kukichalang/kukicha/stdlib/shell"
	strpkg "github.com/kukichalang/kukicha/stdlib/string"
	"io"
	"os"
	"path/filepath"
)

//line agent.kuki:12
const defaultSystemPrompt = "You are a helpful assistant with access to a sandboxed Linux environment via tool calls. You can execute commands, read/write files, search, and manage the filesystem. Use these tools to help the user accomplish their goals. Be concise in your explanations but thorough in your tool usage."

//line agent.kuki:14
type Agent struct {
	Bridge       *Bridge
	Config       Config
	SystemPrompt string
	MaxRounds    int
	OnText       func(string)
	OnToolCall   func(string, string)
	OnToolResult func(string, string)
}

//line agent.kuki:23
type RunResult struct {
	Content  string
	Messages []llm.Message
	Rounds   int
}

//line agent.kuki:28
func runAgent(ctx context.Context, a *Agent, userPrompt string, history []llm.Message) (*RunResult, error) {
//line agent.kuki:29
	maxRounds := a.MaxRounds
//line agent.kuki:30
	if maxRounds == 0 {
//line agent.kuki:31
		maxRounds = 15
	}
//line agent.kuki:33
	messages := append([]llm.Message{}, history...)
//line agent.kuki:36
	if len(messages) == 0 {
//line agent.kuki:37
		sys := a.SystemPrompt
//line agent.kuki:38
		if sys == "" {
//line agent.kuki:39
			sys = defaultSystemPrompt
		}
//line agent.kuki:40
		messages = append(messages, llm.Message{Role: "system", Content: sys})
	}
//line agent.kuki:42
	messages = append(messages, llm.Message{Role: "user", Content: userPrompt})
//line agent.kuki:45
	tools := bridgeTools(a.Bridge)
//line agent.kuki:47
	for round := range maxRounds {
//line agent.kuki:49
		client := llm.Messages(llm.APIKey(llm.Path(llm.BaseURL(llm.Model(llm.New(""), a.Config.Model), a.Config.WebUIURL), "/api/chat/completions"), a.Config.WebUIAPIKey), messages)
//line agent.kuki:57
		for _, t := range tools {
//line agent.kuki:58
			client = llm.AddTool(client, t.Function.Name, t.Function.Description, t.Function.Parameters)
		}
//line agent.kuki:61
		if a.OnText != nil {
//line agent.kuki:62
			client = llm.Stream(client, a.OnText)
		}
//line agent.kuki:64
		if len(tools) > 0 {
//line agent.kuki:65
			client = llm.ToolChoiceAuto(client)
		}
//line agent.kuki:68
		comp, err_1 := llm.SendRaw(client)
//line agent.kuki:68
		if err_1 != nil {
//line agent.kuki:68
			return nil, fmt.Errorf("LLM request failed (round %v): %v", round, err_1)
		}
//line agent.kuki:70
		content := llm.GetContent(comp)
//line agent.kuki:75
		if llm.HasToolCalls(comp) {
//line agent.kuki:76
			toolCalls := llm.GetToolCalls(comp)
//line agent.kuki:79
			messages = append(messages, llm.Message{Role: "assistant", Content: content, ToolCalls: toolCalls})
//line agent.kuki:81
			for _, tc := range toolCalls {
//line agent.kuki:82
				if a.OnToolCall != nil {
//line agent.kuki:83
					a.OnToolCall(tc.Function.Name, tc.Function.Arguments)
				}
//line agent.kuki:85
				toolResult, err_2 := callBridgeTool(ctx, a.Bridge, tc.Function.Name, tc.Function.Arguments)
//line agent.kuki:85
				if err_2 != nil {
//line agent.kuki:85
					//line agent.kuki:86
					toolResult = fmt.Sprintf("ERROR: %v", err_2)
				}
//line agent.kuki:88
				if a.OnToolResult != nil {
//line agent.kuki:89
					a.OnToolResult(tc.Function.Name, truncateStr(toolResult, 500))
				}
//line agent.kuki:92
				messages = append(messages, llm.Message{Role: "tool", Content: toolResult, ToolCallID: tc.ID})
			}
//line agent.kuki:94
			continue
		}
//line agent.kuki:97
		return &RunResult{Content: content, Messages: messages, Rounds: (round + 1)}, nil
	}
//line agent.kuki:99
	return nil, fmt.Errorf("agent hit max rounds (%v) without completing", maxRounds)
}

//line agent.kuki:101
func truncateStr(s string, n int) string {
//line agent.kuki:102
	if len(s) <= n {
//line agent.kuki:103
		return s
	}
//line agent.kuki:104
	return (s[:n] + "...")
}

//line bridge.kuki:13
type ToolRoute struct {
	ServerName   string
	OriginalName string
}

//line bridge.kuki:17
type BridgeServer struct {
	Name    string
	URL     string
	Session *mcp.ClientSession
	Tools   []mcp.ClientTool
}

//line bridge.kuki:23
type Bridge struct {
	Servers        []*BridgeServer
	ToolMap        map[string]ToolRoute
	LocalTools     LocalTools
	LocalToolNames map[string]bool
}

//line bridge.kuki:29
func connectBridges(ctx context.Context, configs map[string]MCPServerConfig) (*Bridge, error) {
//line bridge.kuki:30
	b := &Bridge{Servers: make([]*BridgeServer, 0), ToolMap: make(map[string]ToolRoute), LocalToolNames: make(map[string]bool)}
//line bridge.kuki:36
	for name, cfg := range configs {
//line bridge.kuki:37
		session, err := connectOne(ctx, cfg)
//line bridge.kuki:38
		if err != nil {
//line bridge.kuki:39
			continue
		}
//line bridge.kuki:41
		server := &BridgeServer{Name: name, URL: cfg.URL, Session: session}
//line bridge.kuki:44
		tools, toolsErr := mcp.ListTools(ctx, session)
//line bridge.kuki:45
		if toolsErr != nil {
//line bridge.kuki:46
			mcp.Close(session)
//line bridge.kuki:47
			continue
		}
//line bridge.kuki:49
		server.Tools = tools
//line bridge.kuki:50
		b.Servers = append(b.Servers, server)
//line bridge.kuki:53
		for _, t := range tools {
//line bridge.kuki:54
			prefixed := fmt.Sprintf("%v_%v", name, sanitizeName(t.Name))
//line bridge.kuki:55
			b.ToolMap[prefixed] = ToolRoute{ServerName: name, OriginalName: t.Name}
		}
	}
//line bridge.kuki:57
	return b, nil
}

//line bridge.kuki:59
func connectOne(ctx context.Context, cfg MCPServerConfig) (*mcp.ClientSession, error) {
//line bridge.kuki:60
	if cfg.APIKey != "" {
//line bridge.kuki:61
		return mcp.BearerConnect(ctx, cfg.URL, cfg.APIKey)
	}
//line bridge.kuki:63
	return mcp.Connect(ctx, cfg.URL)
}

//line bridge.kuki:65
func closeBridges(b *Bridge) error {
//line bridge.kuki:66
	for _, s := range b.Servers {
//line bridge.kuki:67
		mcp.Close(s.Session)
	}
//line bridge.kuki:68
	if len(b.LocalToolNames) > 0 {
//line bridge.kuki:69
//line bridge.kuki:69
		err_3 := closeLocalTools(b.LocalTools)
//line bridge.kuki:69
		if err_3 != nil {
//line bridge.kuki:69
			return nil
		}
	}
//line bridge.kuki:70
	return nil
}

//line bridge.kuki:73
func bridgeTools(b *Bridge) []llm.Tool {
//line bridge.kuki:74
	tools := make([]llm.Tool, 0, (len(b.ToolMap) + len(b.LocalToolNames)))
//line bridge.kuki:76
	if len(b.LocalToolNames) > 0 {
//line bridge.kuki:77
		tools = append(tools, localToolDefs()...)
	}
//line bridge.kuki:79
	for _, s := range b.Servers {
//line bridge.kuki:80
		for _, t := range s.Tools {
//line bridge.kuki:81
			prefixed := fmt.Sprintf("%v_%v", s.Name, sanitizeName(t.Name))
//line bridge.kuki:82
			tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: prefixed, Description: fmt.Sprintf("(%v) %v", s.Name, t.Description), Parameters: t.InputSchema}})
		}
	}
//line bridge.kuki:91
	return tools
}

//line bridge.kuki:93
func bridgeToolCount(b *Bridge) int {
//line bridge.kuki:94
	count := len(b.LocalToolNames)
//line bridge.kuki:95
	for _, s := range b.Servers {
//line bridge.kuki:96
		count = (count + len(s.Tools))
	}
//line bridge.kuki:97
	return count
}

//line bridge.kuki:99
func bridgeToolNames(b *Bridge) []string {
//line bridge.kuki:100
	names := make([]string, 0, (len(b.ToolMap) + len(b.LocalToolNames)))
//line bridge.kuki:101
	for name := range b.LocalToolNames {
//line bridge.kuki:102
		names = append(names, name)
	}
//line bridge.kuki:103
	for prefixed := range b.ToolMap {
//line bridge.kuki:104
		names = append(names, prefixed)
	}
//line bridge.kuki:105
	return names
}

//line bridge.kuki:108
func callBridgeTool(ctx context.Context, b *Bridge, name string, argsJSON string) (string, error) {
//line bridge.kuki:109
	_, isLocal := b.LocalToolNames[name]
//line bridge.kuki:110
	if isLocal {
//line bridge.kuki:111
		return dispatchLocalTool(b.LocalTools, name, argsJSON)
	}
//line bridge.kuki:113
	route, ok := b.ToolMap[name]
//line bridge.kuki:114
	if !ok {
//line bridge.kuki:115
		return "", fmt.Errorf("unknown tool: %v", name)
	}
//line bridge.kuki:117
	for _, s := range b.Servers {
//line bridge.kuki:118
		if s.Name == route.ServerName {
//line bridge.kuki:119
			args := make(map[string]any)
//line bridge.kuki:120
			if (argsJSON != "") && (argsJSON != "{}") {
//line bridge.kuki:121
//line bridge.kuki:121
				err_4 := jsonpkg.UnmarshalString(argsJSON, &args)
//line bridge.kuki:121
				if err_4 != nil {
//line bridge.kuki:121
					return "", fmt.Errorf("invalid tool arguments: %v", err_4)
				}
			}
//line bridge.kuki:123
			result, err := mcp.CallTool(ctx, s.Session, route.OriginalName, args)
//line bridge.kuki:124
			if err != nil {
//line bridge.kuki:125
				return "", err
			}
//line bridge.kuki:127
			if result.IsError {
//line bridge.kuki:128
				return fmt.Sprintf("ERROR: %v", result.Text), nil
			}
//line bridge.kuki:130
			return result.Text, nil
		}
	}
//line bridge.kuki:132
	return "", fmt.Errorf("server %v not connected", route.ServerName)
}

//line bridge.kuki:134
func sanitizeName(name string) string {
//line bridge.kuki:135
	result := strpkg.ReplaceAll(name, "/", "_")
//line bridge.kuki:136
	result = strpkg.ReplaceAll(result, " ", "_")
//line bridge.kuki:137
	result = strpkg.ReplaceAll(result, "-", "_")
//line bridge.kuki:138
	return result
}

//line config.kuki:12
type MCPServerConfig struct {
	URL    string `json:"url"`
	APIKey string `json:"api_key"`
}

//line config.kuki:16
type Config struct {
	WebUIURL          string                     `json:"webui_url"`
	WebUIAPIKey       string                     `json:"webui_api_key"`
	Model             string                     `json:"model"`
	MCPServers        map[string]MCPServerConfig `json:"mcp_servers"`
	TerminalMCPURL    string                     `json:"terminal_mcp_url"`
	TerminalMCPAPIKey string                     `json:"terminal_mcp_api_key"`
	MaxToolRounds     int                        `json:"max_tool_rounds"`
	SandboxDir        string                     `json:"sandbox_dir"`
	IPAllowList       []string                   `json:"ip_allow"`
	IPBlockList       []string                   `json:"ip_block"`
	CmdAllowList      []string                   `json:"cmd_allow"`
}

//line config.kuki:29
func defaultConfigPath() string {
//line config.kuki:30
	home, _ := os.UserHomeDir()
//line config.kuki:31
	return filepath.Join(home, ".config", "owui", "config.json")
}

//line config.kuki:33
func loadConfig() Config {
//line config.kuki:34
	cfg := Config{WebUIURL: "http://localhost:3000", TerminalMCPURL: "http://127.0.0.1:9000/mcp", Model: "llama3.1", MaxToolRounds: 15, MCPServers: make(map[string]MCPServerConfig), IPAllowList: make([]string, 0), IPBlockList: make([]string, 0), CmdAllowList: make([]string, 0)}
//line config.kuki:46
	data, err_5 := files.ReadString(defaultConfigPath())
//line config.kuki:46
	if err_5 != nil {
//line config.kuki:46
		data = ""
	}
//line config.kuki:47
	if data != "" {
//line config.kuki:48
//line config.kuki:48
		err_6 := jsonpkg.UnmarshalString(data, &cfg)
//line config.kuki:48
		if err_6 != nil {
//line config.kuki:48

		}
	}
//line config.kuki:50
	if cfg.MCPServers == nil {
//line config.kuki:51
		cfg.MCPServers = make(map[string]MCPServerConfig)
	}
//line config.kuki:54
	v := env.GetOr("OWUI_WEBUI_URL", "")
//line config.kuki:55
	if v != "" {
//line config.kuki:56
		cfg.WebUIURL = v
	}
//line config.kuki:58
	v = env.GetOr("OWUI_WEBUI_API_KEY", "")
//line config.kuki:59
	if v != "" {
//line config.kuki:60
		cfg.WebUIAPIKey = v
	}
//line config.kuki:62
	v = env.GetOr("OWUI_MODEL", "")
//line config.kuki:63
	if v != "" {
//line config.kuki:64
		cfg.Model = v
	}
//line config.kuki:66
	v = env.GetOr("OWUI_TERMINAL_MCP_URL", "")
//line config.kuki:67
	if v != "" {
//line config.kuki:68
		cfg.TerminalMCPURL = v
	}
//line config.kuki:70
	v = env.GetOr("OWUI_TERMINAL_MCP_API_KEY", "")
//line config.kuki:71
	if v != "" {
//line config.kuki:72
		cfg.TerminalMCPAPIKey = v
	}
//line config.kuki:74
	if cfg.TerminalMCPURL != "" {
//line config.kuki:75
		cfg.MCPServers["terminal"] = MCPServerConfig{URL: cfg.TerminalMCPURL, APIKey: cfg.TerminalMCPAPIKey}
	}
//line config.kuki:77
	v = env.GetOr("OWUI_SANDBOX_DIR", "")
//line config.kuki:78
	if v != "" {
//line config.kuki:79
		cfg.SandboxDir = v
	}
//line config.kuki:81
	return cfg
}

//line config.kuki:83
func saveConfig(cfg Config) error {
//line config.kuki:84
	path := defaultConfigPath()
//line config.kuki:85
//line config.kuki:85
	err_7 := os.MkdirAll(filepath.Dir(path), 0700)
//line config.kuki:85
	if err_7 != nil {
//line config.kuki:85
		return fmt.Errorf("%v", err_7)
	}
//line config.kuki:86
//line config.kuki:86
	err_8 := files.Write(cfg, path)
//line config.kuki:86
	if err_8 != nil {
//line config.kuki:86
		return err_8
	}
//line config.kuki:87
	return nil
}

//line config.kuki:89
func validateConfig(cfg Config) error {
//line config.kuki:90
	if cfg.WebUIAPIKey == "" {
//line config.kuki:91
		return errors.New("Open WebUI API key required: set OWUI_WEBUI_API_KEY or run `owui configure`")
	}
//line config.kuki:92
	return nil
}

//line local_tools.kuki:21
func defaultCmdAllowList() []string {
//line local_tools.kuki:22
	return []string{"cargo", "cat", "cp", "diff", "echo", "env", "find", "git", "go", "grep", "head", "ls", "make", "mkdir", "mv", "node", "npm", "pip3", "pwd", "python3", "rm", "sort", "tail", "touch", "uniq", "wc", "which"}
}

//line local_tools.kuki:30
type LocalTools struct {
	Box         sandbox.Root
	Guard       netguard.Guard
	HasGuard    bool
	AllowedCmds map[string]bool
}

//line local_tools.kuki:38
func buildLocalTools(cfg Config) (LocalTools, error) {
//line local_tools.kuki:39
	lt := LocalTools{AllowedCmds: make(map[string]bool)}
//line local_tools.kuki:41
	sandboxDir := cfg.SandboxDir
//line local_tools.kuki:42
	if sandboxDir == "" {
//line local_tools.kuki:43
		cwd, err_9 := os.Getwd()
//line local_tools.kuki:43
		if err_9 != nil {
//line local_tools.kuki:43
			err_9 = fmt.Errorf("sandbox cwd: %w", err_9)
			var _zero0 LocalTools
//line local_tools.kuki:43
			return _zero0, err_9
		}
//line local_tools.kuki:44
		sandboxDir = cwd
	}
//line local_tools.kuki:46
	box, err_10 := sandbox.New(sandboxDir)
//line local_tools.kuki:46
	if err_10 != nil {
//line local_tools.kuki:46
		err_10 = fmt.Errorf("sandbox: %w", err_10)
		var _zero0 LocalTools
//line local_tools.kuki:46
		return _zero0, err_10
	}
//line local_tools.kuki:47
	lt.Box = box
//line local_tools.kuki:49
	if len(cfg.IPAllowList) > 0 {
//line local_tools.kuki:50
		g, err_11 := netguard.NewAllow(cfg.IPAllowList)
//line local_tools.kuki:50
		if err_11 != nil {
//line local_tools.kuki:50
			err_11 = fmt.Errorf("netguard allow: %w", err_11)
			var _zero0 LocalTools
//line local_tools.kuki:50
			return _zero0, err_11
		}
//line local_tools.kuki:51
		lt.Guard = g
//line local_tools.kuki:52
		lt.HasGuard = true
	} else if len(cfg.IPBlockList) > 0 {
//line local_tools.kuki:54
		g, err_12 := netguard.NewBlock(cfg.IPBlockList)
//line local_tools.kuki:54
		if err_12 != nil {
//line local_tools.kuki:54
			err_12 = fmt.Errorf("netguard block: %w", err_12)
			var _zero0 LocalTools
//line local_tools.kuki:54
			return _zero0, err_12
		}
//line local_tools.kuki:55
		lt.Guard = g
//line local_tools.kuki:56
		lt.HasGuard = true
	}
//line local_tools.kuki:58
	allowed := cfg.CmdAllowList
//line local_tools.kuki:59
	if len(allowed) == 0 {
//line local_tools.kuki:60
		allowed = defaultCmdAllowList()
	}
//line local_tools.kuki:61
	for _, cmd := range allowed {
//line local_tools.kuki:62
		lt.AllowedCmds[cmd] = true
	}
//line local_tools.kuki:64
	return lt, nil
}

//line local_tools.kuki:66
func closeLocalTools(lt LocalTools) error {
//line local_tools.kuki:67
	return sandbox.Close(lt.Box)
}

//line local_tools.kuki:70
func registerLocalTools(b *Bridge, cfg Config) error {
//line local_tools.kuki:71
	lt, err_13 := buildLocalTools(cfg)
//line local_tools.kuki:71
	if err_13 != nil {
//line local_tools.kuki:71
		return err_13
	}
//line local_tools.kuki:72
	b.LocalTools = lt
//line local_tools.kuki:73
	for _, name := range []string{"read_file", "write_file", "list_dir", "search_files", "grep_files", "run_command"} {
//line local_tools.kuki:74
		b.LocalToolNames[name] = true
	}
//line local_tools.kuki:75
	return nil
}

//line local_tools.kuki:79
func strProp(desc string) any {
//line local_tools.kuki:80
	p := make(map[string]any)
//line local_tools.kuki:81
	p["type"] = "string"
//line local_tools.kuki:82
	p["description"] = desc
//line local_tools.kuki:83
	return p
}

//line local_tools.kuki:85
func toolSchema(props map[string]any, required []string) any {
//line local_tools.kuki:86
	s := make(map[string]any)
//line local_tools.kuki:87
	s["type"] = "object"
//line local_tools.kuki:88
	s["properties"] = props
//line local_tools.kuki:89
	s["required"] = required
//line local_tools.kuki:90
	return s
}

//line local_tools.kuki:94
func localToolDefs() []llm.Tool {
//line local_tools.kuki:95
	tools := make([]llm.Tool, 0, 6)
//line local_tools.kuki:97
	readProps := make(map[string]any)
//line local_tools.kuki:98
	readProps["path"] = strProp("File path relative to sandbox root")
//line local_tools.kuki:99
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "read_file", Description: "Read the contents of a file within the sandbox", Parameters: toolSchema(readProps, []string{"path"})}})
//line local_tools.kuki:108
	writeProps := make(map[string]any)
//line local_tools.kuki:109
	writeProps["path"] = strProp("File path relative to sandbox root")
//line local_tools.kuki:110
	writeProps["content"] = strProp("Content to write")
//line local_tools.kuki:111
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "write_file", Description: "Write or overwrite a file within the sandbox", Parameters: toolSchema(writeProps, []string{"path", "content"})}})
//line local_tools.kuki:120
	listProps := make(map[string]any)
//line local_tools.kuki:121
	listProps["path"] = strProp("Directory path relative to sandbox root (default: .)")
//line local_tools.kuki:122
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "list_dir", Description: "List files and directories within a sandbox directory", Parameters: toolSchema(listProps, make([]string, 0))}})
//line local_tools.kuki:131
	searchProps := make(map[string]any)
//line local_tools.kuki:132
	searchProps["pattern"] = strProp("File name glob pattern (e.g. *.go, main.*)")
//line local_tools.kuki:133
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "search_files", Description: "Search for files matching a name pattern within the sandbox", Parameters: toolSchema(searchProps, []string{"pattern"})}})
//line local_tools.kuki:142
	grepProps := make(map[string]any)
//line local_tools.kuki:143
	grepProps["pattern"] = strProp("Regex or literal text to search for")
//line local_tools.kuki:144
	grepProps["path"] = strProp("Path within sandbox to search (default: .)")
//line local_tools.kuki:145
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "grep_files", Description: "Search file contents for a pattern within the sandbox", Parameters: toolSchema(grepProps, []string{"pattern"})}})
//line local_tools.kuki:154
	argsItem := make(map[string]any)
//line local_tools.kuki:155
	argsItem["type"] = "string"
//line local_tools.kuki:156
	argsArr := make(map[string]any)
//line local_tools.kuki:157
	argsArr["type"] = "array"
//line local_tools.kuki:158
	argsArr["items"] = argsItem
//line local_tools.kuki:159
	argsArr["description"] = "Command arguments"
//line local_tools.kuki:160
	runProps := make(map[string]any)
//line local_tools.kuki:161
	runProps["cmd"] = strProp("Command name — allowed: cargo cat cp diff echo find git go grep head ls make mkdir mv node npm pip3 pwd python3 rm sort tail touch uniq wc which")
//line local_tools.kuki:162
	runProps["args"] = argsArr
//line local_tools.kuki:163
	tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: "run_command", Description: "Run an allowlisted shell command in the sandbox directory", Parameters: toolSchema(runProps, []string{"cmd"})}})
//line local_tools.kuki:172
	return tools
}

//line local_tools.kuki:176
func dispatchLocalTool(lt LocalTools, name string, argsJSON string) (string, error) {
//line local_tools.kuki:177
	switch name {
	case "read_file":
//line local_tools.kuki:179
		return localReadFile(lt, argsJSON)
	case "write_file":
//line local_tools.kuki:181
		return localWriteFile(lt, argsJSON)
	case "list_dir":
//line local_tools.kuki:183
		return localListDir(lt, argsJSON)
	case "search_files":
//line local_tools.kuki:185
		return localSearchFiles(lt, argsJSON)
	case "grep_files":
//line local_tools.kuki:187
		return localGrepFiles(lt, argsJSON)
	case "run_command":
//line local_tools.kuki:189
		return localRunCommand(lt, argsJSON)
	default:
//line local_tools.kuki:191
		return "", fmt.Errorf("unknown local tool: %v", name)
	}
}

//line local_tools.kuki:195
type readFileArgs struct {
	Path string `json:"path"`
}

//line local_tools.kuki:198
type writeFileArgs struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

//line local_tools.kuki:202
type listDirArgs struct {
	Path string `json:"path"`
}

//line local_tools.kuki:205
type searchFilesArgs struct {
	Pattern string `json:"pattern"`
}

//line local_tools.kuki:208
type grepFilesArgs struct {
	Pattern string `json:"pattern"`
	Path    string `json:"path"`
}

//line local_tools.kuki:212
type runCommandArgs struct {
	Cmd  string   `json:"cmd"`
	Args []string `json:"args"`
}

//line local_tools.kuki:218
func localReadFile(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:219
	a := readFileArgs{}
//line local_tools.kuki:220
//line local_tools.kuki:220
	err_14 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:220
	if err_14 != nil {
//line local_tools.kuki:220
		return "", fmt.Errorf("read_file: bad args: %v", err_14)
	}
//line local_tools.kuki:221
	if a.Path == "" {
//line local_tools.kuki:222
		return "", errors.New("read_file: missing path")
	}
//line local_tools.kuki:223
	content, err_15 := sandbox.ReadString(lt.Box, a.Path)
//line local_tools.kuki:223
	if err_15 != nil {
//line local_tools.kuki:223
		return "", fmt.Errorf("read_file: %v", err_15)
	}
//line local_tools.kuki:224
	return content, nil
}

//line local_tools.kuki:226
func localWriteFile(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:227
	a := writeFileArgs{}
//line local_tools.kuki:228
//line local_tools.kuki:228
	err_16 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:228
	if err_16 != nil {
//line local_tools.kuki:228
		return "", fmt.Errorf("write_file: bad args: %v", err_16)
	}
//line local_tools.kuki:229
	if a.Path == "" {
//line local_tools.kuki:230
		return "", errors.New("write_file: missing path")
	}
//line local_tools.kuki:231
//line local_tools.kuki:231
	err_17 := sandbox.WriteString(lt.Box, a.Content, a.Path)
//line local_tools.kuki:231
	if err_17 != nil {
//line local_tools.kuki:231
		return "", fmt.Errorf("write_file: %v", err_17)
	}
//line local_tools.kuki:232
	return fmt.Sprintf("wrote %v bytes to %v", len(a.Content), a.Path), nil
}

//line local_tools.kuki:234
func localListDir(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:235
	a := listDirArgs{}
//line local_tools.kuki:236
	if (argsJSON != "") && (argsJSON != "{}") {
//line local_tools.kuki:237
//line local_tools.kuki:237
		err_18 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:237
		if err_18 != nil {
//line local_tools.kuki:237
			return "", fmt.Errorf("list_dir: bad args: %v", err_18)
		}
	}
//line local_tools.kuki:238
	path := a.Path
//line local_tools.kuki:239
	if path == "" {
//line local_tools.kuki:240
		path = "."
	}
//line local_tools.kuki:241
	names, err_19 := sandbox.List(lt.Box, path)
//line local_tools.kuki:241
	if err_19 != nil {
//line local_tools.kuki:241
		return "", fmt.Errorf("list_dir: %v", err_19)
	}
//line local_tools.kuki:242
	if len(names) == 0 {
//line local_tools.kuki:243
		return "(empty)", nil
	}
//line local_tools.kuki:244
	return strpkg.Join(names, "\n"), nil
}

//line local_tools.kuki:246
func localSearchFiles(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:247
	a := searchFilesArgs{}
//line local_tools.kuki:248
//line local_tools.kuki:248
	err_20 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:248
	if err_20 != nil {
//line local_tools.kuki:248
		return "", fmt.Errorf("search_files: bad args: %v", err_20)
	}
//line local_tools.kuki:249
	if a.Pattern == "" {
//line local_tools.kuki:250
		return "", errors.New("search_files: missing pattern")
	}
//line local_tools.kuki:251
	sandboxPath := sandbox.Path(lt.Box)
//line local_tools.kuki:252
	out := shell.Execute(shell.New("find", sandboxPath, "-name", a.Pattern))
//line local_tools.kuki:253
	raw := strpkg.TrimSpace(string(shell.GetOutput(out)))
//line local_tools.kuki:254
	if raw == "" {
//line local_tools.kuki:255
		return "(no matches)", nil
	}
//line local_tools.kuki:256
	prefix := (sandboxPath + "/")
//line local_tools.kuki:257
	lines := strpkg.Split(raw, "\n")
//line local_tools.kuki:258
	results := make([]string, 0, len(lines))
//line local_tools.kuki:259
	for _, line := range lines {
//line local_tools.kuki:260
		if line != "" {
//line local_tools.kuki:261
			results = append(results, strpkg.TrimPrefix(line, prefix))
		}
	}
//line local_tools.kuki:262
	return strpkg.Join(results, "\n"), nil
}

//line local_tools.kuki:264
func localGrepFiles(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:265
	a := grepFilesArgs{}
//line local_tools.kuki:266
//line local_tools.kuki:266
	err_21 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:266
	if err_21 != nil {
//line local_tools.kuki:266
		return "", fmt.Errorf("grep_files: bad args: %v", err_21)
	}
//line local_tools.kuki:267
	if a.Pattern == "" {
//line local_tools.kuki:268
		return "", errors.New("grep_files: missing pattern")
	}
//line local_tools.kuki:269
	sandboxPath := sandbox.Path(lt.Box)
//line local_tools.kuki:270
	searchPath := a.Path
//line local_tools.kuki:271
	if searchPath == "" {
//line local_tools.kuki:272
		searchPath = "."
	}
//line local_tools.kuki:273
	fullPath := filepath.Join(sandboxPath, searchPath)
//line local_tools.kuki:274
	rel, err_22 := filepath.Rel(sandboxPath, fullPath)
//line local_tools.kuki:274
	if err_22 != nil {
//line local_tools.kuki:274
		return "", errors.New("grep_files: invalid path")
	}
//line local_tools.kuki:275
	if strpkg.HasPrefix(rel, "..") {
//line local_tools.kuki:276
		return "", errors.New("grep_files: path escapes sandbox")
	}
//line local_tools.kuki:277
	out := shell.Execute(shell.New("grep", "-r", "-n", a.Pattern, fullPath))
//line local_tools.kuki:278
	raw := strpkg.TrimSpace(string(shell.GetOutput(out)))
//line local_tools.kuki:279
	if raw == "" {
//line local_tools.kuki:280
		return "(no matches)", nil
	}
//line local_tools.kuki:281
	prefix := (sandboxPath + "/")
//line local_tools.kuki:282
	lines := strpkg.Split(raw, "\n")
//line local_tools.kuki:283
	results := make([]string, 0, len(lines))
//line local_tools.kuki:284
	for _, line := range lines {
//line local_tools.kuki:285
		if line != "" {
//line local_tools.kuki:286
			results = append(results, strpkg.TrimPrefix(line, prefix))
		}
	}
//line local_tools.kuki:287
	return strpkg.Join(results, "\n"), nil
}

//line local_tools.kuki:289
func localRunCommand(lt LocalTools, argsJSON string) (string, error) {
//line local_tools.kuki:290
	a := runCommandArgs{}
//line local_tools.kuki:291
//line local_tools.kuki:291
	err_23 := jsonpkg.UnmarshalString(argsJSON, &a)
//line local_tools.kuki:291
	if err_23 != nil {
//line local_tools.kuki:291
		return "", fmt.Errorf("run_command: bad args: %v", err_23)
	}
//line local_tools.kuki:292
	if a.Cmd == "" {
//line local_tools.kuki:293
		return "", errors.New("run_command: missing cmd")
	}
//line local_tools.kuki:294
	_, ok := lt.AllowedCmds[a.Cmd]
//line local_tools.kuki:295
	if !ok {
//line local_tools.kuki:296
		return "", fmt.Errorf("run_command: '%v' is not in the allowed command list", a.Cmd)
	}
//line local_tools.kuki:297
	sandboxPath := sandbox.Path(lt.Box)
//line local_tools.kuki:298
	out := shell.Execute(shell.Dir(shell.New(a.Cmd, a.Args...), sandboxPath))
//line local_tools.kuki:299
	stdout := strpkg.TrimSpace(string(shell.GetOutput(out)))
//line local_tools.kuki:300
	stderr := strpkg.TrimSpace(string(shell.GetError(out)))
//line local_tools.kuki:301
	combined := stdout
//line local_tools.kuki:302
	if stderr != "" {
//line local_tools.kuki:303
		if combined != "" {
//line local_tools.kuki:304
			combined = fmt.Sprintf("%v\n[stderr]\n%v", combined, stderr)
		} else {
//line local_tools.kuki:306
			combined = fmt.Sprintf("[stderr]\n%v", stderr)
		}
	}
//line local_tools.kuki:307
	if combined == "" {
//line local_tools.kuki:308
		combined = "(no output)"
	}
//line local_tools.kuki:309
	if !shell.Success(out) {
//line local_tools.kuki:310
		return combined, fmt.Errorf("exited %v", shell.ExitCode(out))
	}
//line local_tools.kuki:311
	return combined, nil
}

//line main.kuki:19
var version string = "dev"

//line main.kuki:22
const ansiReset = "\x1b[0m"

//line main.kuki:24
const ansiDim = "\x1b[2m"

//line main.kuki:26
const ansiYellow = "\x1b[33m"

//line main.kuki:28
const ansiBoldYellow = "\x1b[1;33m"

//line main.kuki:30
const ansiBoldCyan = "\x1b[1;36m"

//line main.kuki:32
const ansiRed = "\x1b[91m"

//line main.kuki:34
const ansiGreen = "\x1b[32m"

//line main.kuki:36
func dimFmt(s string) string {
//line main.kuki:37
	return fmt.Sprintf("%v%v%v", ansiDim, s, ansiReset)
}

//line main.kuki:39
func toolFmt(s string) string {
//line main.kuki:40
	return fmt.Sprintf("%v%v%v", ansiYellow, s, ansiReset)
}

//line main.kuki:42
func errFmt(s string) string {
//line main.kuki:43
	return fmt.Sprintf("%v%v%v", ansiRed, s, ansiReset)
}

//line main.kuki:45
func greenFmt(s string) string {
//line main.kuki:46
	return fmt.Sprintf("%v%v%v", ansiGreen, s, ansiReset)
}

//line main.kuki:48
func boldCyanFmt(s string) string {
//line main.kuki:49
	return fmt.Sprintf("%v%v%v", ansiBoldCyan, s, ansiReset)
}

//line main.kuki:51
func boldYellowFmt(s string) string {
//line main.kuki:52
	return fmt.Sprintf("%v%v%v", ansiBoldYellow, s, ansiReset)
}

//line main.kuki:56
func main() {
//line main.kuki:57
	args := os.Args[1:]
//line main.kuki:60
	flagModel := ""
//line main.kuki:61
	flagChat := false
//line main.kuki:62
	flagRaw := false
//line main.kuki:63
	flagSystem := ""
//line main.kuki:64
	positional := make([]string, 0)
//line main.kuki:66
	i := 0
//line main.kuki:67
	for i < len(args) {
//line main.kuki:68
		arg := args[i]
//line main.kuki:69
		if (arg == "-m") || (arg == "--model") {
//line main.kuki:70
			i = (i + 1)
//line main.kuki:71
			if i < len(args) {
//line main.kuki:72
				flagModel = args[i]
			}
		} else if strpkg.HasPrefix(arg, "--model=") {
//line main.kuki:74
			flagModel = strpkg.TrimPrefix(arg, "--model=")
		} else if (arg == "-c") || (arg == "--chat") {
//line main.kuki:76
			flagChat = true
		} else if arg == "--raw" {
//line main.kuki:78
			flagRaw = true
		} else if (arg == "-S") || (arg == "--system") {
//line main.kuki:80
			i = (i + 1)
//line main.kuki:81
			if i < len(args) {
//line main.kuki:82
				flagSystem = args[i]
			}
		} else if strpkg.HasPrefix(arg, "--system=") {
//line main.kuki:84
			flagSystem = strpkg.TrimPrefix(arg, "--system=")
		} else if (arg == "-h") || (arg == "--help") {
//line main.kuki:86
			printUsage()
//line main.kuki:87
			return
		} else {
//line main.kuki:89
			positional = append(positional, arg)
		}
//line main.kuki:90
		i = (i + 1)
	}
//line main.kuki:93
	if len(positional) > 0 {
//line main.kuki:94
		cmd := positional[0]
//line main.kuki:95
		if cmd == "models" {
//line main.kuki:96
//line main.kuki:96
			err_24 := cmdListModels()
//line main.kuki:96
			if err_24 != nil {
//line main.kuki:96
				//line main.kuki:97
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_24)))
			}
//line main.kuki:99
			return
		}
//line main.kuki:100
		if cmd == "tools" {
//line main.kuki:101
//line main.kuki:101
			err_25 := cmdListTools()
//line main.kuki:101
			if err_25 != nil {
//line main.kuki:101
				//line main.kuki:102
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_25)))
			}
//line main.kuki:104
			return
		}
//line main.kuki:105
		if cmd == "health" {
//line main.kuki:106
//line main.kuki:106
			err_26 := cmdHealth()
//line main.kuki:106
			if err_26 != nil {
//line main.kuki:106
				//line main.kuki:107
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_26)))
			}
//line main.kuki:109
			return
		}
//line main.kuki:110
		if cmd == "configure" {
//line main.kuki:111
//line main.kuki:111
			err_27 := cmdConfigure()
//line main.kuki:111
			if err_27 != nil {
//line main.kuki:111
				//line main.kuki:112
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_27)))
			}
//line main.kuki:114
			return
		}
//line main.kuki:115
		if cmd == "version" {
//line main.kuki:116
			fmt.Println(fmt.Sprintf("owui %v", version))
//line main.kuki:117
			return
		}
	}
//line main.kuki:120
//line main.kuki:120
	err_28 := cmdRun(positional, flagModel, flagChat, flagRaw, flagSystem)
//line main.kuki:120
	if err_28 != nil {
//line main.kuki:120
		//line main.kuki:121
		cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_28)))
	}
}

//line main.kuki:125
func cmdRun(positional []string, flagModel string, flagChat bool, flagRaw bool, flagSystem string) error {
//line main.kuki:126
	cfg := loadConfig()
//line main.kuki:127
	if flagModel != "" {
//line main.kuki:128
		cfg.Model = flagModel
	}
//line main.kuki:129
//line main.kuki:129
	err_29 := validateConfig(cfg)
//line main.kuki:129
	if err_29 != nil {
//line main.kuki:129
		return err_29
	}
//line main.kuki:131
	ctx := context.Background()
//line main.kuki:133
	bridge, err_30 := connectBridges(ctx, cfg.MCPServers)
//line main.kuki:133
	if err_30 != nil {
//line main.kuki:133
		return fmt.Errorf("connecting to MCP servers: %v", err_30)
	}
//line main.kuki:134
	defer closeBridges(bridge)
//line main.kuki:136
//line main.kuki:136
	err_31 := registerLocalTools(bridge, cfg)
//line main.kuki:136
	if err_31 != nil {
//line main.kuki:136
		//line main.kuki:137
		fmt.Fprint(os.Stderr, fmt.Sprintf("%v\n", dimFmt(fmt.Sprintf("warning: local tools unavailable: %v", err_31))))
	}
//line main.kuki:139
	if isTTYErr() {
//line main.kuki:140
		sandboxLabel := func() string {
			if cfg.SandboxDir != "" {
				return cfg.SandboxDir
			} else {
				return "cwd"
			}
		}()
//line main.kuki:141
		fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", dimFmt("tools:"), dimFmt(fmt.Sprintf("%v available | sandbox: %v", bridgeToolCount(bridge), sandboxLabel))))
	}
//line main.kuki:143
	a := &Agent{Bridge: bridge, Config: cfg, MaxRounds: cfg.MaxToolRounds}
//line main.kuki:145
	if flagSystem != "" {
//line main.kuki:146
		a.SystemPrompt = flagSystem
	}
//line main.kuki:149
	agentsDoc, err_32 := files.ReadString("AGENTS.md")
//line main.kuki:149
	if err_32 != nil {
//line main.kuki:149
		agentsDoc = ""
	}
//line main.kuki:150
	if agentsDoc != "" {
//line main.kuki:151
		base := a.SystemPrompt
//line main.kuki:152
		if base == "" {
//line main.kuki:153
			base = defaultSystemPrompt
		}
//line main.kuki:154
		a.SystemPrompt = fmt.Sprintf("%v\n\n# Project Context (AGENTS.md)\n\n%v", base, agentsDoc)
//line main.kuki:155
		if isTTYErr() {
//line main.kuki:156
			fmt.Fprint(os.Stderr, fmt.Sprintf("%v\n", dimFmt("Loaded AGENTS.md from current directory")))
		}
	}
//line main.kuki:158
	prompt := gatherPrompt(positional)
//line main.kuki:161
	if flagChat {
//line main.kuki:162
		runChat(ctx, a, prompt)
//line main.kuki:163
		return nil
	}
//line main.kuki:166
	if prompt == "" {
//line main.kuki:167
		return errors.New("no prompt provided — use -c for interactive chat")
	}
//line main.kuki:169
	isTTY := isTTYOut()
//line main.kuki:171
	if isTTY {
//line main.kuki:172
		a.OnToolCall = func(name string, toolArgs string) {
//line main.kuki:173
			fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", toolFmt(fmt.Sprintf("-> %v", name)), dimFmt(truncateFmt(toolArgs, 80))))
		}
//line main.kuki:175
		a.OnToolResult = func(name string, result string) {
//line main.kuki:176
			fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", toolFmt(fmt.Sprintf("<- %v", name)), dimFmt(truncateFmt(result, 120))))
		}
	}
//line main.kuki:178
	a.OnText = func(chunk string) {
//line main.kuki:179
		if isTTY && !flagRaw {
//line main.kuki:180
			fmt.Print(chunk)
		}
	}
//line main.kuki:182
	result, err_33 := runAgent(ctx, a, prompt, []llm.Message{})
//line main.kuki:182
	if err_33 != nil {
//line main.kuki:182
		return err_33
	}
//line main.kuki:184
	if isTTY && !flagRaw {
//line main.kuki:185
		fmt.Println()
	} else {
//line main.kuki:187
		fmt.Print(result.Content)
	}
//line main.kuki:189
	if isTTY {
//line main.kuki:190
		fmt.Fprint(os.Stderr, fmt.Sprintf("%v\n", dimFmt(fmt.Sprintf("(%v tool rounds)", result.Rounds))))
	}
//line main.kuki:192
	return nil
}

//line main.kuki:196
type ModelEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

//line main.kuki:200
type ModelsResponse struct {
	Data []ModelEntry `json:"data"`
}

//line main.kuki:203
func cmdListModels() error {
//line main.kuki:204
	cfg := loadConfig()
//line main.kuki:205
	if cfg.WebUIAPIKey == "" {
//line main.kuki:206
		return errors.New("Open WebUI API key required")
	}
//line main.kuki:208
	url := fmt.Sprintf("%v/api/models", strpkg.TrimRight(cfg.WebUIURL, "/"))
//line main.kuki:209
	// pipe step 1: fetch.Do(...)
//line main.kuki:209
	resp, err_35 := fetch.Do(fetch.BearerAuth(fetch.New(url), cfg.WebUIAPIKey))
//line main.kuki:209
	if err_35 != nil {
//line main.kuki:209
		return err_35
	}
//line main.kuki:211
	defer resp.Body.Close()
//line main.kuki:213
	if resp.StatusCode != 200 {
//line main.kuki:214
		body, err_36 := fetch.Bytes(resp)
//line main.kuki:214
		if err_36 != nil {
//line main.kuki:214
			return fmt.Errorf("HTTP %v", resp.StatusCode)
		}
//line main.kuki:215
		return fmt.Errorf("HTTP %v: %v", resp.StatusCode, string(body))
	}
//line main.kuki:217
	models := ModelsResponse{}
//line main.kuki:218
//line main.kuki:218
	err_37 := jsonpkg.UnmarshalRead(resp.Body, &models)
//line main.kuki:218
	if err_37 != nil {
//line main.kuki:218
		return err_37
	}
//line main.kuki:220
	fmt.Println(boldCyanFmt("Available models:"))
//line main.kuki:221
	for _, m := range models.Data {
//line main.kuki:222
		name := m.Name
//line main.kuki:223
		if name == "" {
//line main.kuki:224
			name = m.ID
		}
//line main.kuki:225
		fmt.Println(fmt.Sprintf("  %v %v", name, dimFmt(fmt.Sprintf("(%v)", m.ID))))
	}
//line main.kuki:227
	return nil
}

//line main.kuki:229
func cmdListTools() error {
//line main.kuki:230
	cfg := loadConfig()
//line main.kuki:231
	ctx := context.Background()
//line main.kuki:233
	bridge, err_38 := connectBridges(ctx, cfg.MCPServers)
//line main.kuki:233
	if err_38 != nil {
//line main.kuki:233
		return err_38
	}
//line main.kuki:234
	defer closeBridges(bridge)
//line main.kuki:236
//line main.kuki:236
	err_39 := registerLocalTools(bridge, cfg)
//line main.kuki:236
	if err_39 != nil {
//line main.kuki:236
		return err_39
	}
//line main.kuki:238
	fmt.Println(boldYellowFmt("Available tools:"))
//line main.kuki:239
	for _, name := range bridgeToolNames(bridge) {
//line main.kuki:240
		fmt.Println(fmt.Sprintf("  %v", name))
	}
//line main.kuki:242
	return nil
}

//line main.kuki:244
func cmdHealth() error {
//line main.kuki:245
	cfg := loadConfig()
//line main.kuki:246
	ctx := context.Background()
//line main.kuki:249
	fmt.Printf("Open WebUI  (%v)  ", cfg.WebUIURL)
//line main.kuki:250
	if cfg.WebUIAPIKey != "" {
//line main.kuki:251
		url := fmt.Sprintf("%v/api/models", strpkg.TrimRight(cfg.WebUIURL, "/"))
//line main.kuki:252
		resp, err := fetch.Do(fetch.BearerAuth(fetch.New(url), cfg.WebUIAPIKey))
//line main.kuki:254
		if err != nil {
//line main.kuki:255
			fmt.Println(errFmt("x"), err)
		} else {
//line main.kuki:257
			resp.Body.Close()
//line main.kuki:258
			if resp.StatusCode == 200 {
//line main.kuki:259
				fmt.Println(greenFmt("ok"))
			} else {
//line main.kuki:261
				fmt.Println(errFmt("x"), fmt.Sprintf("HTTP %v", resp.StatusCode))
			}
		}
	} else {
//line main.kuki:263
		fmt.Println(errFmt("x"), "no API key")
	}
//line main.kuki:266
	for name, mcfg := range cfg.MCPServers {
//line main.kuki:267
		fmt.Printf("%v MCP (%v)  ", name, mcfg.URL)
//line main.kuki:268
		m := make(map[string]MCPServerConfig)
//line main.kuki:269
		m[name] = mcfg
//line main.kuki:270
		bridge, err := connectBridges(ctx, m)
//line main.kuki:271
		if err != nil {
//line main.kuki:272
			fmt.Println(errFmt("x"), err)
		} else {
//line main.kuki:274
			fmt.Println(greenFmt("ok"), fmt.Sprintf("%v tools", bridgeToolCount(bridge)))
//line main.kuki:275
			closeBridges(bridge)
		}
	}
//line main.kuki:277
	return nil
}

//line main.kuki:279
func cmdConfigure() error {
//line main.kuki:280
	cfg := loadConfig()
//line main.kuki:282
	v, err_40 := input.ReadLine(fmt.Sprintf("Open WebUI URL [%v]: ", cfg.WebUIURL))
//line main.kuki:282
	if err_40 != nil {
//line main.kuki:282
		v = ""
	}
//line main.kuki:283
	if v != "" {
//line main.kuki:284
		cfg.WebUIURL = v
	}
//line main.kuki:286
	var err_41 error
	v, err_41 = input.ReadLine(fmt.Sprintf("Open WebUI API Key [%v]: ", maskKey(cfg.WebUIAPIKey)))
//line main.kuki:286
	if err_41 != nil {
//line main.kuki:286
		v = ""
	}
//line main.kuki:287
	if v != "" {
//line main.kuki:288
		cfg.WebUIAPIKey = v
	}
//line main.kuki:290
	var err_42 error
	v, err_42 = input.ReadLine(fmt.Sprintf("Model [%v]: ", cfg.Model))
//line main.kuki:290
	if err_42 != nil {
//line main.kuki:290
		v = ""
	}
//line main.kuki:291
	if v != "" {
//line main.kuki:292
		cfg.Model = v
	}
//line main.kuki:294
	var err_43 error
	v, err_43 = input.ReadLine(fmt.Sprintf("terminal MCP URL [%v]: ", cfg.TerminalMCPURL))
//line main.kuki:294
	if err_43 != nil {
//line main.kuki:294
		v = ""
	}
//line main.kuki:295
	if v != "" {
//line main.kuki:296
		cfg.TerminalMCPURL = v
	}
//line main.kuki:298
	var err_44 error
	v, err_44 = input.ReadLine(fmt.Sprintf("terminal MCP API Key [%v]: ", maskKey(cfg.TerminalMCPAPIKey)))
//line main.kuki:298
	if err_44 != nil {
//line main.kuki:298
		v = ""
	}
//line main.kuki:299
	if v != "" {
//line main.kuki:300
		cfg.TerminalMCPAPIKey = v
	}
//line main.kuki:302
	var err_45 error
	v, err_45 = input.ReadLine(fmt.Sprintf("Sandbox directory [%v]: ", cfg.SandboxDir))
//line main.kuki:302
	if err_45 != nil {
//line main.kuki:302
		v = ""
	}
//line main.kuki:303
	if v != "" {
//line main.kuki:304
		cfg.SandboxDir = v
	}
//line main.kuki:306
//line main.kuki:306
	err_46 := saveConfig(cfg)
//line main.kuki:306
	if err_46 != nil {
//line main.kuki:306
		return err_46
	}
//line main.kuki:307
	fmt.Println(greenFmt(fmt.Sprintf("Saved to %v", defaultConfigPath())))
//line main.kuki:308
	return nil
}

//line main.kuki:312
func runChat(ctx context.Context, a *Agent, initialPrompt string) {
//line main.kuki:313
	history := []llm.Message{}
//line main.kuki:314
	prompt := initialPrompt
//line main.kuki:316
	fmt.Println(dimFmt(fmt.Sprintf("owui chat — model: %v — type 'exit' to quit", a.Config.Model)))
//line main.kuki:317
	fmt.Println("")
//line main.kuki:319
	for {
//line main.kuki:320
		if prompt == "" {
//line main.kuki:321
			var err_47 error
			prompt, err_47 = input.ReadLine(boldCyanFmt("you> "))
//line main.kuki:321
			if err_47 != nil {
//line main.kuki:321
				break
			}
//line main.kuki:322
			if (prompt == "exit") || (prompt == "quit") {
//line main.kuki:323
				break
			}
//line main.kuki:324
			if prompt == "" {
//line main.kuki:325
				continue
			}
		}
//line main.kuki:327
		a.OnToolCall = func(name string, toolArgs string) {
//line main.kuki:328
			fmt.Fprint(os.Stderr, fmt.Sprintf("  %v %v\n", toolFmt(fmt.Sprintf("-> %v", name)), dimFmt(truncateFmt(toolArgs, 60))))
		}
//line main.kuki:330
		a.OnToolResult = func(name string, result string) {
//line main.kuki:331
			fmt.Fprint(os.Stderr, fmt.Sprintf("  %v %v\n", toolFmt(fmt.Sprintf("<- %v", name)), dimFmt(truncateFmt(result, 80))))
		}
//line main.kuki:335
		firstChunk := true
//line main.kuki:336
		a.OnText = func(chunk string) {
//line main.kuki:337
			if firstChunk {
//line main.kuki:338
				fmt.Print(fmt.Sprintf("\n%v  ", dimFmt(a.Config.Model)))
//line main.kuki:339
				firstChunk = false
			}
//line main.kuki:340
			fmt.Print(chunk)
		}
//line main.kuki:342
		result, err_48 := runAgent(ctx, a, prompt, history)
//line main.kuki:342
		if err_48 != nil {
//line main.kuki:342
			//line main.kuki:343
			fmt.Println(errFmt(fmt.Sprintf("error: %v", err_48)))
			//line main.kuki:344
			fmt.Println("")
			//line main.kuki:345
			prompt = ""
			//line main.kuki:346
			continue
		}
//line main.kuki:348
		if firstChunk && (result.Content != "") {
//line main.kuki:350
			fmt.Println(fmt.Sprintf("\n%v  %v", dimFmt(a.Config.Model), result.Content))
		} else {
//line main.kuki:352
			fmt.Println()
		}
//line main.kuki:353
		if result.Rounds > 1 {
//line main.kuki:354
			fmt.Println(dimFmt(fmt.Sprintf("  (%v rounds)", result.Rounds)))
		}
//line main.kuki:355
		fmt.Println("")
//line main.kuki:357
		history = result.Messages
//line main.kuki:358
		prompt = ""
	}
}

//line main.kuki:362
func gatherPrompt(args []string) string {
//line main.kuki:363
	prompt := ""
//line main.kuki:366
	if !isTerminal(os.Stdin) && (len(args) == 0) {
//line main.kuki:367
		data, _ := io.ReadAll(os.Stdin)
//line main.kuki:368
		prompt = strpkg.TrimSpace(string(data))
	}
//line main.kuki:370
	if len(args) > 0 {
//line main.kuki:371
		argText := strpkg.Join(args, " ")
//line main.kuki:372
		if prompt != "" {
//line main.kuki:373
			prompt = fmt.Sprintf("%v\n\n%v", argText, prompt)
		} else {
//line main.kuki:375
			prompt = argText
		}
	}
//line main.kuki:377
	return prompt
}

//line main.kuki:379
func isTerminal(f *os.File) bool {
//line main.kuki:380
	info, err := f.Stat()
//line main.kuki:381
	if err != nil {
//line main.kuki:382
		return false
	}
//line main.kuki:383
	return ((info.Mode() & 0x200000) != 0)
}

//line main.kuki:385
func isTTYOut() bool {
//line main.kuki:386
	return isTerminal(os.Stdout)
}

//line main.kuki:388
func isTTYErr() bool {
//line main.kuki:389
	return isTerminal(os.Stderr)
}

//line main.kuki:391
func maskKey(k string) string {
//line main.kuki:392
	if len(k) < 8 {
//line main.kuki:393
		return "--------"
	}
//line main.kuki:394
	return fmt.Sprintf("%v...%v", k[:4], k[(len(k)-4):])
}

//line main.kuki:396
func truncateFmt(s string, n int) string {
//line main.kuki:397
	s = strpkg.ReplaceAll(s, "\n", " ")
//line main.kuki:398
	if len(s) <= n {
//line main.kuki:399
		return s
	}
//line main.kuki:400
	return fmt.Sprintf("%v...", s[:n])
}

//line main.kuki:402
func printUsage() {
//line main.kuki:403
	fmt.Println("owui — CLI agent: Open WebUI models + Open Terminal via MCP")
//line main.kuki:404
	fmt.Println("")
//line main.kuki:405
	fmt.Println("Usage:")
//line main.kuki:406
	fmt.Println("  owui [flags] [prompt]     Agent mode (one-shot or piped)")
//line main.kuki:407
	fmt.Println("  owui -c [prompt]          Interactive chat")
//line main.kuki:408
	fmt.Println("  owui models               List available models")
//line main.kuki:409
	fmt.Println("  owui tools                List MCP tools")
//line main.kuki:410
	fmt.Println("  owui health               Check connectivity")
//line main.kuki:411
	fmt.Println("  owui configure            Save configuration")
//line main.kuki:412
	fmt.Println("  owui version              Print version")
//line main.kuki:413
	fmt.Println("")
//line main.kuki:414
	fmt.Println("Flags:")
//line main.kuki:415
	fmt.Println("  -m, --model <model>       Override model")
//line main.kuki:416
	fmt.Println("  -c, --chat                Interactive chat mode")
//line main.kuki:417
	fmt.Println("  -S, --system <prompt>     Override system prompt")
//line main.kuki:418
	fmt.Println("  --raw                     Raw output (no formatting)")
//line main.kuki:419
	fmt.Println("")
//line main.kuki:420
	fmt.Println("Environment:")
//line main.kuki:421
	fmt.Println("  OWUI_WEBUI_URL            Open WebUI URL (default: http://localhost:3000)")
//line main.kuki:422
	fmt.Println("  OWUI_WEBUI_API_KEY        Open WebUI API key (required)")
//line main.kuki:423
	fmt.Println("  OWUI_MODEL                Model name (default: llama3.1)")
//line main.kuki:424
	fmt.Println("  OWUI_TERMINAL_MCP_URL     terminal MCP URL (default: http://127.0.0.1:9000/mcp)")
//line main.kuki:425
	fmt.Println("  OWUI_TERMINAL_MCP_API_KEY terminal MCP API key (optional, for authenticated servers)")
//line main.kuki:426
	fmt.Println("  OWUI_SANDBOX_DIR          sandbox root for built-in tools (default: cwd)")
}
